package org.charism;
/*

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"


Constraints:

        0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

public class FindTheDifference {
    public static void main(String[] args) {
        FindTheDifference f = new FindTheDifference();
        System.out.println(f.findTheDifference("abcd", "abcde"));
        System.out.println(f.findTheDifference("", "y"));
        System.out.println(f.findTheDifference("a", "aa"));
    }

    public char findTheDifference(String s, String t) {
        for (char c : t.toCharArray()) {
            if (s.indexOf(c) == -1) {
                return c;
            } else {
                s = s.replaceFirst(String.valueOf(c), "");
            }
        }
        return ' ';
    }
}
